[tool.poetry]
name = "angband"
version = "0.1.0"
description = ""
authors = ["Pat Wick"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"
retro-games = "^0.1.2"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
